version: '3.8'
services:
  oereb-db:
    image: ghcr.io/agiktsh/ch.sh.oereb_server.database.2.oereb_themes:latest
    restart: unless-stopped
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    environment:
      POSTGRES_DB: oereb
    ports:
      - 54323:5432
  webservice:
    # image: docker.io/sogis/oereb-web-service:2.0.1708
    # image: docker.io/sogis/oereb-web-service:2.0.1723
    # image: docker.io/sogis/oereb-web-service:2.0.1711
    image: docker.io/sogis/oereb-web-service:2.0.1807
    restart: unless-stopped
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    deploy:
      replicas: 1
    environment:
      TZ: Europe/Zurich
      # DBURL: jdbc:postgresql://oereb-db:5432/oereb
      # DBUSR: dmluser
      # DBPWD: 1HIwBLNCoETJFYq5nGSY
      # TMPDIR: /work
      # DBSCHEMA: live
      # MININTERSECTION: "0.1"
      # CADASTRE_AUTHORITY_URL: https://agi.sh.ch
      # PLAN_FOR_LANDREGISTER: https://geodienste.ch/db/av_situationsplan_oereb_0/deu?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=av_situationsplan_oereb&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=675&WIDTH=1920&HEIGHT=710&BBOX=2607051.2375,1228517.0374999999,2608067.2375,1228892.7458333333
      # PLAN_FOR_LANDREGISTER_MAIN_PAGE: https://geodienste.ch/db/av_situationsplan_0/deu??SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=av_situationsplan&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=675&WIDTH=1920&HEIGHT=710&BBOX=2607051.2375,1228517.0374999999,2608067.2375,1228892.7458333333
    ports:
      - 8080:8080
    depends_on:
      - oereb-db
    entrypoint: "java -Xmx2G -jar oereb-web-service-docker.jar"
    command:
      - "--server.tomcat.threads.max=200"
      - "--server.tomcat.accept-count=100"
      - "--server.tomcat.max-connections=10000"
      - "--management.endpoint.health.probes.enabled=false"
      - "--management.health.livenessState.enabled=false"
      - "--management.health.readinessState.enabled=false"
      - "--spring.datasource.hikari.maximum-pool-size=10"
      - "--spring.datasource.url=jdbc:postgresql://oereb-db:5432/oereb?ApplicationName=oereb-web-service"
      - "--spring.datasource.username=dmluser"
      - "--spring.datasource.password=1HIwBLNCoETJFYq5nGSY"
      - "--oereb.tmpdir=/work"
      - "--oereb.dbschema=live"
      - "--oereb.minIntersection=0.1"
      - "--oereb.canton=Schaffhausen"
      - "--oereb.dpi=200"
      - "--oereb.cadastreAuthorityUrl=https://agi.sh.ch"
      - "--oereb.planForLandregister=https://geodienste.ch/db/av_situationsplan_oereb_0/deu?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=av_situationsplan_oereb&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=675&WIDTH=1920&HEIGHT=710&BBOX=2607051.2375,1228517.0374999999,2608067.2375,1228892.7458333333"
      - "--oereb.planForLandregisterMainPage=https://geodienste.ch/db/av_situationsplan_0/deu?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=av_situationsplan&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=675&WIDTH=1920&HEIGHT=710&BBOX=2607051.2375,1228517.0374999999,2608067.2375,1228892.7458333333"
      - "--oereb.webAppUrl=https://map.geo.sh.ch/oereb?egrid="
      - "--spring.datasource.driver-class-name=org.postgresql.Driver"
      - "--logging.level.com.zaxxer.hikari=trace"
      - "--logging.level.org.springframework.jdbc.core.JdbcTemplate=warn"
      - "--logging.level.org.springframework.web=warn"
      - "--logging.level.ch.ehi.oereb=warn"
      # - "--logging.level.ch.ehi.oereb=info"
